# Generated by Django 5.1.5 on 2025-08-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone_num',
            field=models.CharField(default='251912345678', max_length=22),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='class_room',
            field=models.CharField(default='9A', max_length=4),
        ),
    ]
