# Generated by Django 5.2.4 on 2025-08-03 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_subject_grade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
