# Generated by Django 5.2.4 on 2025-08-17 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_users_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('A', 'Annual')], max_length=10)),
                ('rank', models.PositiveIntegerField()),
                ('calculation_date', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='core.student')),
            ],
            options={
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
